version: '2'

volumes:
  db:

networks:
  internal:
    external: false

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
  app:
    image: nextcloud_maps_dev
    build: ./nextcloud-docker/17.0/apache
    links:
      - db
    volumes:
      - ./src/:/opt/
      - ./www/:/var/www/html/
    restart: always
    networks:
      - internal
    ports:
      - 8000:80
