version: '3'

volumes:
  db:

networks:
  internal:
    external: false

services:
  db:
    image: mariadb
    container_name: nc_maps_dev_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
  app:
    container_name: nc_maps_dev_app
    build: .
    links:
      - db
    volumes:
      - ./src/:/opt/
      - ./www/:/var/www/html/
    restart: always
    networks:
      - internal
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=webserver
      - APACHE_RUN_GROUP=webserver
